production: &prod
  adapter: postgresql
  encoding: unicode
  database: websiteone_production
  pool: 5
  username: postgres
  password:

# development: &dev
#   <<: *prod
#   database: websiteone_development

# test: &test
#   <<: *dev
#   database: websiteone_test

development: &dev
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test: &test
  <<: *dev
  database: db/test.sqlite3

cucumber:
  <<: *test
